#!/bin/bash
#
# BSPWM config file
#

sxhkd &

bspc config border_width        1
bspc config window_gap          4

for m in $(bspc query -M); do
    bspc monitor $m -d 1 2 3 4 5
done

bspc config split_ratio         0.5
bspc config gapless_monocle     true
bspc config borderless_monocle  true

bspc config focus_follows_pointer true

bspc config focused_border_color $(xrdb -q|grep color1\:|cut -f2)
bspc config normal_border_color $(xrdb -q|grep color8\:|cut -f2)
