#!/bin/bash
#
# BSPWM config file
#

bspc config border_width		1
bspc config window_gap			4

bspc monitor -d 1 2 3

bspc config top_padding			20

bspc config split_ratio			0.5
bspc config gapless_monocle		true
bspc config borderless_monocle	true

bspc config focus_follows_pointer true

bspc config focused_border_color \#6699cc
bspc config active_border_color  \#a09f93
bspc config normal_border_color  \#2d2d2d
bspc config presel_border_color  \#747369

bspc config focused_locked_border_color \#ffcc66
bspc config active_locked_border_color  \#f99157
bspc config normal_locked_border_color  \#f2777a

bspc config focused_sticky_border_color \#6699cc
bspc config active_sticky_border_color  \#6699cc
bspc config normal_sticky_border_color  \#66cccc

bspc config focused_private_border_color \#d27b53
bspc config active_private_border_color  \#d27b53
bspc config normal_private_border_color  \#d27b53

bspc config urgent_border_color \#cc99cc
