#!/bin/bash
#
# BSPWM config file
#

bspc config border_width		1
bspc config window_gap			4

bspc monitor -d 1 2 3 4 5

bspc config top_padding			24

bspc config split_ratio			0.5
bspc config gapless_monocle		true
bspc config borderless_monocle	true

bspc config focus_follows_pointer true

bspc config focused_border_color \#A0A0A0
bspc config active_border_color  \#202020
bspc config normal_border_color  \#202020
bspc config presel_border_color  \#202020

bspc config focused_locked_border_color \#a54242
bspc config active_locked_border_color  \#a54242
bspc config normal_locked_border_color  \#a54242

bspc config focused_sticky_border_color \#8c9440
bspc config active_sticky_border_color  \#8c9440
bspc config normal_sticky_border_color  \#8c9440

bspc config focused_private_border_color \#85678f
bspc config active_private_border_color  \#85678f
bspc config normal_private_border_color  \#85678f

bspc config urgent_border_color \#de935f
